name: CD - Dev

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy-dev:
    name: Deploy Dev
    concurrency:
      group: ${{ format('{0}-{1}', github.workflow, github.job) }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: development
      environment_url: https://static.dev.astro-aws.org/
      stack_environment: DEV
    secrets: inherit
