name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 20
        cmd:
          - build
          - test
          - lint
          - prettier
          - synth
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "8.7.6"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::738697399292:role/GitHubOIDCReadOnlyRole
          aws-region: us-west-2
      - run: pnpm install
      - run: pnpm run ${{ matrix.cmd }}
